### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by x-sNOw** [MirageZoe/better-discord-antispam#2]
ReportChannel.send is not a function.

It created a channel called antispam-logs to log there. But sadly nothing logs there and it recreates a new different channel everytime.

It DMs me with this:

Oops, seems like i dont have sufficient permissions to mut <@user>! (it mutes the user just doesn’t log the mute)

It can be that or another type of error happened! Tell me on github and it links me here.

ReportChannel.send is not a function

P.S if this is the first time getting something like this, most likely because it was not set good the log channel at the beginning and didnt know where to send the reports. Do not panic, next time it will work since he created the channel where to send the reports.

It wasnt the first time and the bot does not create the channel to log the events at

**Comment by MirageZoe** [comment]
Hello,

Sorry for late reply but can you write the settings you used for the log-channel? 
if it has any kind of uppercase letter, please change it to lowercase:

AntiSpam-logs > antispam-logs

Tell me if this fixed the problem!

**Comment by TijsDeBelie** [comment]
Same error and used the default settings that were included on the npm package

**Comment by jkzh0u** [comment]
SAME

**Comment by jkzh0u** [comment]
I have fixed it!
![image](https://user-images.githubusercontent.com/48633565/77459818-a8c2f780-6dd6-11ea-8cf8-bee87f8a9414.png)
![image](https://user-images.githubusercontent.com/48633565/77459843-aeb8d880-6dd6-11ea-8746-9b5a7c4e475c.png)
I just changed it, and it worked!
