### ISSUE TITLE
get a type error 

### ISSUE THREAD

**Issue by m8besoft** [MirageZoe/better-discord-antispam#3]
![image](https://user-images.githubusercontent.com/13623479/79074744-72bbc800-7d31-11ea-9b04-ba9e023a741d.png)

![image](https://user-images.githubusercontent.com/13623479/79074778-9e3eb280-7d31-11ea-8fed-bdfbe03544c7.png)

**Comment by m8besoft** [comment]
![image](https://user-images.githubusercontent.com/13623479/79074911-87e52680-7d32-11ea-8baa-24733caab214.png)

also forgot to mention i get this everytime someone is meant to get muted and when it tries to mute it creates a new role and doesnt mute at all

**Comment by MirageZoe** [comment]
Hello, I'm sorry for late reply. From what I can see, I can guess you're using the latest discord.js version, v12, right? I forgot to update it with the release of v12 but I'll update it as soon as I can. For now this is the only problem I can think so far of.

**Comment by MirageZoe** [comment]
@m8besoft I have updated the npm module and now if you update, it should work :100: % unless something unexpected happens :).
If you get over more issues, please do not hesitate to open a new issue ticket!
