### ISSUE TITLE
Correct some english on Auto Mute log

### ISSUE THREAD

**Issue by cades66** [MirageZoe/better-discord-antispam#4]
https://raimu.is-for.me/i/3gz8edno.png

I apologize to be nitpicky, but I thought it'd look cleaner.

 - Change "How much time got muted?:" to "Mute Length:"
 - Change "Reason of mute:" to "Mute Reason:"
 - Change "When it was muted that person:" to "Time of Action:"

**Comment by MirageZoe** [comment]
Hello, thank you for the suggestion. I'll think about it in the next update which will bring as well a new thing but you'll see that when it comes ^^.
