### ISSUE TITLE
giving the error <ignoredRoles> option is not set up right! Please check it again to be an array in settings.

### ISSUE THREAD

**Issue by typicalninja** [MirageZoe/better-discord-antispam#7]
i tried to setup this in a discord js v12 but it would always give the error `<ignoredRoles> option is not set up right! Please check it again to be an array in settings.` 

i will include my bots code here  
https://hatebin.com/rlvmiycpon

this is similar to both bots

```
}})
 client.on('ready', () => {
  // Module Configuration Constructor
   antispam(client, {
        limitUntilWarn: 3, 
        limitUntilMuted: 5, 
        interval: 2000, 
        warningMessage: "if you don't stop from spamming, I'm going to punish you!", 
        muteMessage: "was muted since we don't like too much advertisement type people!", 
        maxDuplicatesWarning: 7,
        maxDuplicatesMute: 10, 
        ignoredRoles: ["owner"], 
        ignoredMembers: ["Axix#9144"],
        mutedRole: "muted", 
        timeMuted: 1000 * 600, 
        logChannel: "antispam-logs" 
      });
});
 
client.on('message', msg => {
  client.emit('checkMessage', msg);
});
```

even when I copyed it from the github code the error is same

**Comment by typicalninja** [comment]
if i delte the options ignored mebers and roles it works

**Comment by k-tten** [comment]
maybe it can't find those roles?

**Comment by k-tten** [comment]
anyways this should be an easy fix, make a pull request

**Comment by k-tten** [comment]
ok i checked the code and you should just use `new Array()` instead... i dont know why an array literal doesnt work
